Added Logo proposals
PDG2023/GameSync.App pull request #110
Opened 2023-08-31 21:35 UTC by kjorand

Proposal of a logo

Original files available in the second repo

2023-09-01 11:19 UTC, bchollet commented
Sympa le logo 👍 

Je suis moins convaincu par la favicon. Ca ressemble à un "Danger d'électrocution"

![image](https://github.com/PDG2023/GameSync.App/assets/43602096/31b9db58-7c4d-462d-9f6f-141fff783423)

2023-09-01 11:23 UTC, bchollet requested changes

2023-09-01 11:23 UTC, bchollet commented on GameSync.Api/wwwroot/favicon.ico
Pas très convaincu par la favicon. Ca ressemble à un "Danger d'électrocution, non ?

![image](https://github.com/PDG2023/GameSync.App/assets/43602096/927a0c6f-972d-4f46-8ee6-9d2576a60628)

2023-09-01 11:23 UTC, bchollet commented on GameSync.Api/wwwroot/img/Logo.webp
Sympa le logo 👍 
Tu penses pouvoir en faire un png sans le fond ?

2023-09-02 08:10 UTC, kjorand commented on GameSync.Api/wwwroot/img/Logo.webp
Oui bien sûr !!!
Easy chill ... 
Webp sans le fond ... ça te convient aussi (c'est plus moderne/léger ... ^^) ?

2023-09-02 08:14 UTC, kjorand commented on GameSync.Api/wwwroot/favicon.ico
C'est vrai ... j'avais pas fait le lien ... J'ai juste pris le G et intégré le S dedans ... ^^ (mais je dois avouer qu'à choisir .... je le préfère quand même à celui qui ressemble à un bouclier d'antivirus ^^ [#celui d'Angular] )

![image](https://github.com/PDG2023/GameSync.App/assets/25977492/13b830e1-e413-408b-a781-41360fe0da35)

En vrai avec la couleur ... je trouve que ça va encore ... 

Mais pour moi on peut changer ... je suis juste un peu en panne d'inspi !

Une idée peut-être ???

2023-09-03 11:30 UTC, bchollet commented on GameSync.Api/wwwroot/img/Logo.webp
Oui. C'est juste pour l'afficher proprement sur l'application 😄

2023-09-03 11:32 UTC, bchollet commented on GameSync.Api/wwwroot/favicon.ico
Oui, j'avais bien compris que c'était un G et un S imbriqué.
Si tu n'as pas d'autres idées, je n'en ai pas spécialement non plus (je suis pas designer 🤷‍♂️ )

2023-09-03 19:50 UTC, kjorand commented on GameSync.Api/wwwroot/img/Logo.webp
Done

2023-09-05 17:57 UTC, Fl4gu1z0wsky approved these changes

2023-09-07 09:39 UTC, bchollet approved these changes

2023-09-07 09:39 UTC, merged